function Hd = bandpass_filter_v3(order,c1_freq,c2_freq,sampling_frequency)
%BANDPASS_FILTER_V3 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 19-Nov-2020 18:18:46

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = sampling_frequency;  % Sampling Frequency

N             = order;      % Order
Fc1           = c1_freq;      % First Cutoff Frequency
Fc2           = c2_freq;    % Second Cutoff Frequency
flag          = 'scale';  % Sampling Flag
SidelobeAtten = 1000;      % Window Parameter
% Create the window vector for the design algorithm.
win = chebwin(N+1, SidelobeAtten);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
