function Hd = bandpass_filter_v1
%BANDPASS_FILTER_V1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 14-Nov-2020 20:35:51

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 3600;  % Sampling Frequency

N   = 10;    % Order
Fc1 = 100;   % First Cutoff Frequency
Fc2 = 1680;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

% [EOF]
