function Hd = bandpass_filter_v2(order,c1_freq,c2_freq,sampling_frequency)
%BANDPASS_FILTER_V2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 19-Nov-2020 17:24:06

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = sampling_frequency;  % Sampling Frequency

N      = order;   % Order
Fstop1 = c1_freq;   % First Stopband Frequency
Fstop2 = c2_freq;  % Second Stopband Frequency
Astop  = 100;   % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass('N,Fst1,Fst2,Ast', N, Fstop1, Fstop2, Astop, Fs);
Hd = design(h, 'cheby2');

% [EOF]
