function Hd = lowpass_FIR_v2_chebyshev(order, cutoff_frequency, sampling_frequency)
%LOWPASS_FIR_V2_CHEBYSHEV Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 04-Dec-2020 12:06:10

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
% All frequency values are in Hz.
Fs = sampling_frequency;  % Sampling Frequency

N  = order;   % Order
Fc = cutoff_frequency;  % Cutoff Frequency     % Cutoff Frequency
flag          = 'scale';  % Sampling Flag
SidelobeAtten = 100;      % Window Parameter

% Create the window vector for the design algorithm.
win = chebwin(N+1, SidelobeAtten);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
